# Tasks to run on workspace start
tasks:
  - name: Setup Node.js & PostgreSQL
    init: |
      # 1. Setup Node.js v20
      nvm install 20 && nvm use 20 && nvm alias default 20
      
      # 2. Find and setup PostgreSQL
      echo "Searching for PostgreSQL binaries..."
      PG_BIN_PATH=$(find /usr/lib/postgresql -name "initdb" 2>/dev/null | head -n 1)
      
      if [ -z "$PG_BIN_PATH" ]; then
        echo "ERROR: Could not find PostgreSQL 'initdb' command."
        exit 1
      fi
      
      PG_BIN_DIR=$(dirname "$PG_BIN_PATH")
      echo "Found PostgreSQL executables at: $PG_BIN_DIR"
      
      # 3. Initialize and start the database
      mkdir -p /workspace/pg-data
      "$PG_BIN_DIR/initdb" -D /workspace/pg-data
      "$PG_BIN_DIR/pg_ctl" -D /workspace/pg-data -l logfile start
      
      # 4. Create the user and database
      "$PG_BIN_DIR/psql" -U gitpod -c "CREATE USER solstice_admin WITH PASSWORD 'password';"
      "$PG_BIN_DIR/psql" -U gitpod -c "CREATE DATABASE solstice_db OWNER solstice_admin;"
    command: |
      # Ensure correct environment on every start
      nvm use 20
      PG_CTL_PATH=$(find /usr/lib/postgresql -name "pg_ctl" 2>/dev/null | head -n 1)
      if [ -n "$PG_CTL_PATH" ]; then
        "$PG_CTL_PATH" -D /workspace/pg-data -l logfile start
      fi

# Ports to expose on workspace start
ports:
  - name: Web Server
    description: Port 3000 for the Node.js server
    port: 3000
    onOpen: open-preview